### ISSUE TITLE
Command to show the contents of user's library

### ISSUE THREAD

**Issue by funkycharlie** [funkycharlie/Consolify#2]
When a user types 'library', the program should print a list of everything in the user's library, which is numbered so that each element can be accessed later.

**Comment by ghost** [comment]
Hi I would like to try and fix this issue. could you please assign it to me?

**Comment by funkycharlie** [comment]
> Hi I would like to try and fix this issue. could you please assign it to me?

Yeah that'd be great! Thank you so much

**Comment by funkycharlie** [comment]
Fixed thanks to @PedramHaeri :)
